### ISSUE TITLE
[Feature Request] Also show information about games on GOG

### ISSUE THREAD

**Issue by tiredElephant** [Saulios/RedditSteamGameInfo#6]
The bot is really cool but would it be possible to also get information from gog. 
I don't know how doable this is. 

This api for example seems to give information like price, discounts, publisher, release date, tags and rating by gog users:
https://catalog.gog.com/v1/catalog?countryCode=DE&currencyCode=EUR&limit=20&locale=de-DE&order=desc:score&page=1&productType=in:game,pack,dlc,extras&query=like:Sigma%20Theory:%20Global%20Cold%20War (example for the latest gog game on r/FGF)

Maybe the game could also be searched on Steam and then the bot could display a Steam link. The last part seems pretty "easy" since the bot already does that for Steam posts with non-steam links

I hope you'll consider this.
But thanks anyway for the bot and moderating the subreddit.

**Comment by Saulios** [comment]
Interesting, I was not aware of that API link, seems doable, I will have a look at it, thanks!

**Comment by Saulios** [comment]
Functionality added in commit https://github.com/Saulios/RedditSteamGameInfo/commit/ae55cc63d5f54e22712c4c2cf7f37a369c5b729f
